version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transport_rental_db
    restart: always
    environment:
      POSTGRES_DB: transport_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./transport-rental
    container_name: transport_rental_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transport_rental
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
      - ./transport-rental/uploads:/app/uploads

  frontend:
    build:
      context: ./transport-rental-front
    container_name: transport_rental_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pg_data: