version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transport_rental_db_dev
    restart: always
    environment:
      POSTGRES_DB: transport_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

volumes:
  pg_data_dev: